### ISSUE TITLE
Functions with automatic broadcasting

### ISSUE THREAD

**Issue by billtubbs** [based-robotics/jaxadi#14]
Hi, great initiative, thanks for sharing your work.

I'm just trying out for the first time so sorry if I'm missing something...

Is it possible to make Jax functions from CasADi functions that handle broadcasting?

e.g.
```python
import casadi as cas
from jaxadi import convert

# Make a simple CasADi function
x = cas.SX.sym('x')
y = x ** 2 + 1
my_cas_fn = cas.Function('my_cas_fn', [x], [y], ['x'], ['f(x)'])
print(my_cas_fn(2.0))
print(my_cas_fn([1.0, 2.0, 3.0, 4.0, 5.0]))
```
Output:
```none
DM(5)
DM([2, 5, 10, 17, 26])
```

Convert to Jax
```python
jax_fn = convert(my_cas_fn, compile=True)
print(jax_fn(jnp.array([[2.0]])))
print(jax_fn(jnp.array([1.0, 2.0, 3.0, 4.0, 5.0]).reshape(-1, 1))))
```
Output:
```none
[Array([[5.]], dtype=float32)]
[Array([[2.]], dtype=float32)]
```

**Comment by lvjonok** [comment]
Hello, @billtubbs!

I believe what you are asking is [vmap](https://jax.readthedocs.io/en/latest/_autosummary/jax.vmap.html). It is used in order to evaluate the function with different input parameters. With that in mind, we didn't consider implementing broadcasting in a way CasADi does as there are other more specialized tools for the purpose.

Here is an extension of your example with `broadcasting/batched run`:

```python
import casadi as cas
import jax.numpy as jnp
from jax import vmap

from jaxadi import convert

# Make a simple CasADi function
x = cas.SX.sym("x")
y = x**2 + 1
my_cas_fn = cas.Function("my_cas_fn", [x], [y], ["x"], ["f(x)"])

# Convert to JAX function
jax_fn = convert(my_cas_fn, compile=True)

# Vectorize the function with jax.vmap to handle broadcasting
vmap_jax_fn = vmap(jax_fn)

# Example inputs
N_INPUTS = 1
single_input = jnp.array([2.0]).reshape(N_INPUTS, 1)

N_INPUTS = 5
broadcast_input = jnp.array([1.0, 2.0, 3.0, 4.0, 5.0]).reshape(N_INPUTS, 1)

# Apply the vectorized function
print("Single input:", vmap_jax_fn(single_input)[0].T)
print("Broadcast input:", vmap_jax_fn(broadcast_input)[0].T)
```

Let me know if you run into any more questions!

**Comment by billtubbs** [comment]
Good point. I should be using vmap not relying on broadcasting. Although broadcasting seems to work in Jax so I have been using it and I'm still not sure if I should.

```python
@jit
def jax_fn(x):
    return x**2 + 1
print(jax_fn(jnp.array([1.0, 2.0, 3.0, 4.0, 5.0]).reshape(-1, 1)))
```

Output
```
Array([[ 2.],
       [ 5.],
       [10.],
       [17.],
       [26.]], dtype=float32)
```

**Comment by lvjonok** [comment]
Diving into the implementation details, CasADi uses SX symbols to build a function, and we parse the computation tree. To improve execution time for large functions, we merge expressions, which disables broadcasting since the function must match the exact input size of the CasADi function.

In terms of our library, broadcasting is challenging to implement. However, if a strong need arises, we may prioritize it in the future.

Thanks for your interest, @billtubbs!
