### ISSUE TITLE
Slow execution of converted function on Colab

### ISSUE THREAD

**Issue by billtubbs** [based-robotics/jaxadi#15]
Not sure what I'm doing wrong but I can't get the converted Jax function to run fast.

This is the example from the [Getting Started notebook](https://colab.research.google.com/github/based-robotics/jaxadi/blob/master/examples/_demo.ipynb):

```python
import casadi as cs
from jax import jit
import jax.numpy as jnp
from jaxadi import convert

# Define input variables
x = cs.SX.sym("x", 3, 2)
y = cs.SX.sym("y", 2, 2)
# Define a nonlinear function
z = x @ y  # Matrix multiplication
z_squared = z * z  # Element-wise squaring
z_sin = cs.sin(z)  # Element-wise sine
result = z_squared + z_sin  # Element-wise addition
# Create the CasADi function
casadi_fn = cs.Function("complex_nonlinear_func", [x, y], [result])

@jit
def jax_fn(x, y):
    z = x @ y  # Matrix multiplication
    z_squared = z * z  # Element-wise squaring
    z_sin = jnp.sin(z)  # Element-wise sine
    return z_squared + z_sin  # Element-wise addition

jaxadi_fn = convert(casadi_fn, compile=True)
```

Below is a speed comparison I did on Colab based on the above example:

![Screenshot 2024-10-08 083733](https://github.com/user-attachments/assets/1a64f778-22ba-48ac-8062-822dc860370a)

Here is a [copy of the full script in my github](https://github.com/billtubbs/jax-examples/blob/c9dfaeabf87c4e33c027e081c56b317ee343e998/examples/jaxadi_demo.ipynb).

**Comment by lvjonok** [comment]
Hello @billtubbs!

Thank you for your interest in **jaxadi**!

We have ran your example and indeed the problem is present. Our initial guess is that for such a small function the overhead of generalization. We will perform the tests with previous approaches and will return with the results.

**Comment by mattephi** [comment]
I have profiled the issue for some time. The most time consuming part is at[].set(), six calls of which are present in this particular example. I do not think this issue is fixable, since it is the only way to update the buffer of computations. I do not think it will be possible to achieve native performance anyway, due to how graph of computations decomposes operations which are computed more efficiently in the native implementation.

[perfetto_trace (2).json.gz](https://github.com/user-attachments/files/18050648/perfetto_trace.2.json.gz)

**Comment by billtubbs** [comment]
If this example gives the wrong impression about Jaxadi's performance then maybe don't include it as the first example in the getting started notebook!
